### ISSUE TITLE
service doesn't print

### ISSUE THREAD

**Issue by tve** [procks/direct_print_server#2]
I installed direct print server on windows 7 x84 and it seems to run fine in the foreground or as a service.
I connected to it from an android 5.0.1 tablet using the direct print server app. I can see the list of printers available on my windows machine. I then printed a web page from chrome. I get the print dialog where I can select the pages and I made sure the destination is one of the printers on my windows server (a xerox phaser 6010). The dialog on the tablet closes and I now see a "printing" entry in the notifications pull-down. At this point it has been stuck there for a long time.
How do I troubleshoot this? I looked in the event viewer and don't see anything logged by the windows service. Should I run the app from the commandline?

**Comment by procks** [comment]
Try to try to uninstall and reinstall with StartUp option selected, or just stop service and run Direct Pint Server from start menu. Note: check icon in system tray. Then try print again, and look what happened. Sometimes, for some reason I cannot understand, ghostscript does not understand the value printer name passed and show select printer dialog form. Then stuck until select. You also can try to rename printer in control panel device and printers.

**Comment by tve** [comment]
> Note: check icon in system tray.

The icon is there, but all I can do with it is right-click to stop/exit. Is there supposed to be any status information?

> and look what happened

Look where?

> show select printer dialog form

Where is this form shown?

**Comment by procks** [comment]
Ok, it is other issues. Try install logging version
https://drive.google.com/file/d/0B0nKCKI8LZ-pd0YzMG5iUjVyRlk/view
Then print some document and get "log" и "pdf" from %appdata%\DirectPrint\ (like C:\Users\"user name"\AppData\Roaming\DirectPrint\ "user name" - your user name) and send to olksur@gmail.com . It can halp me undestend the problem.

**Comment by tve** [comment]
Attached is a log file with two printing attempts. In between the two I renamed an Espon printer to remove a '/' in the name. But that didn't help.
[logfile.txt](https://github.com/procks/direct_print_server/files/351579/logfile.txt)

**Comment by tve** [comment]
I noticed that there are two PDF files in DirectPrint's Temp dir. I tried to open them using acrobat and I get an error that the files are corrupt. Dunno whether this is expected or not...

**Comment by procks** [comment]
I recently update protobuf version in Direct Print Service. Looks like I broke backward compatibility :(. Please, let me know if that fixes problem.
[app-release.zip](https://github.com/procks/direct_print_server/files/351614/app-release.zip)

**Comment by tve** [comment]
bed time here, I'll have to try this tomorrow...

**Comment by procks** [comment]
Is there any news?

**Comment by tve** [comment]
Yup, that did it, printing works with this apk! Thanks!
